feature #12
serg-rsv/team-project-02 pull request #46
Opened 2022-06-11 17:23 UTC by Kaplynenko

2022-06-11 18:02 UTC, serg-rsv approved these changes

2022-06-11 18:02 UTC, serg-rsv commented on src/js/services/Oleksandr/render.js
> +const API_KEY = '5ce599886a4c0703a030654068991e03'
ключ є в класі. тут він не потрібен.

2022-06-11 18:02 UTC, serg-rsv commented on src/index.js
> +import './js/services/Oleksandr/render'
коли імпортуєш потрібно вказати що саме.
тут тільки вказано звідки.
поки видали цей імпорт взагалі.

2022-06-11 18:02 UTC, serg-rsv commented on src/partials/main.html
> +
забагато пустіх рядків))
видали 3, 5, 6, 8

2022-06-11 18:02 UTC, serg-rsv commented on src/sass/main.scss
> +@import'./utils/main-site';
потрібно виправити шлях до файлу стилів.
в папці sass створи section-main і перенеси туди свої стилі.
можна окремо створити файл стилів для опису однієї картки фільму і для врапера з сіткою

2022-06-11 18:02 UTC, serg-rsv commented on src/sass/utils/_main-site.scss
> +.container {
класс .container вже описаний в стилях src\sass\base\_container.scss
поки переіменуй його щоб стилі не перебівались. і виправ назву в паршалі де використовуєш.

2022-06-11 18:02 UTC, serg-rsv commented on src/sass/utils/_main-site.scss
> +    width: 992px;
стилі описуемо від мобілки до десктоп.
для мобілки за широко)

2022-06-11 18:02 UTC, serg-rsv commented on src/sass/utils/_main-site.scss
> +        margin-top: 8px;
52-56 зайвий відступ. і далі в 61...
включи прітієр.

2022-06-11 18:02 UTC, serg-rsv commented on src/js/services/Oleksandr/render.js
> +                <p class="film_genre">${genre_ids}</p>
рік випуску, рейтинг забув додати

2022-06-11 18:02 UTC, serg-rsv commented on src/sass/utils/_main-site.scss
> +    display: flex;
тут можна зроби сіткою grid

2022-06-11 18:02 UTC, serg-rsv commented on src/sass/utils/_main-site.scss
> +    flex-wrap: wrap;
здається згубив display: flex.

2022-06-11 18:03 UTC, serg-rsv requested changes
потрібно дещо виправити

2022-06-11 19:45 UTC, Kaplynenko commented on src/index.js
> +import './js/services/Oleksandr/render'
коментив import перестає працювати сторінка

2022-06-12 07:43 UTC, serg-rsv requested changes
ще дещо помітитви. потрібно виправити.

2022-06-12 07:43 UTC, serg-rsv commented on src/sass/utils/_main-site.scss
> +  @media screen and (min-width: 768px) and(max-width:990px) {
в меіда запросах заміни числа на змунні із _variables.scss
```
// Точки перелома
$mobile: 320px;
$tablet: 768px;
$desktop: 1024px;

// Максимальная ширина планшетной версии
$underdesktop: 1023px;
```

2022-06-12 07:43 UTC, serg-rsv commented on src/js/services/Oleksandr/render.js
> +import TmdbApiService from '../tmdb-api';
в src/js/services/ файли для роботи з бекендом. перемісти Oleksandr/render.js в в src/js/

2022-06-12 14:31 UTC, serg-rsv approved these changes

2022-06-12 14:31 UTC, merged